### ISSUE TITLE
Crash when restoring poses backup.

### ISSUE THREAD

**Issue by linkanon** [aa2g/AA2Snowflake#4]
Snowflake also doesn't recognize that it already created a backup. When I click set camera postion it pops up a 

```
---------------------------
Unable to restore
---------------------------
You haven't created a backup, so restoration is not possible.
Are you sure you want to continue?
---------------------------
Yes   No   
---------------------------
```

Even after clicking Backup All beforehand.
[dump](https://mega.nz/#!pd1RULKb!L4wrDb6Hl5hyP5Ft8PVvPZekH_aFmNp8kZSQK_CXEJs)

**Comment by ghost** [comment]
Try this build: https://mega.nz/#!9lsBjbSY!0IdEdMGiPtnPgXW-z5zm2MT99jRf-zLtfXm-Bx_s-Y8

**Comment by linkanon** [comment]
I don't get the popup anymore but it still crashes when restoring the backup.
[dump](https://mega.nz/#!xEcERLZZ!UDsxW4D6V5dtE_BWq71pomebe7DSiChbxaJjDJ2cf5U)

**Comment by ghost** [comment]
This one should do it: https://mega.nz/#!Aoth3Ija!B8joK-Ao-OhRuUSSP-uck_axtE2TpYhVowhzbkb9DzM

You need to create a new backup though

**Comment by linkanon** [comment]
Can confirm it fixed that.
