### ISSUE TITLE
AA2Snowflake 2.0 crash

### ISSUE THREAD

**Issue by ghost** [aa2g/AA2Snowflake#5]
_Moved from [here](https://github.com/aa2g/AA2Install/issues/7)_

Can't even start the program on Windows Vista 32bit.

[AA2Snowflake crash.zip](https://github.com/aa2g/AA2Install/files/197713/AA2Snowflake.crash.zip)

**Comment by ghost** [comment]
@cacass I may have a fix here:
https://mega.nz/#!co1EnDLD!WdlPt9k3ICjw7r6NVF46MV1l1l4xDKREeYJLg7WjUH8

**Comment by cacass** [comment]
Yeah! Now it works!

**Comment by ghost** [comment]
Closed since issue fixed.
