### ISSUE TITLE
We have blank borders now, how long will it be until blank personality/name?

### ISSUE THREAD

**Issue by chlorine03** [aa2g/AA2Snowflake#7]
I'm sure you're busy fixing bugs and/or improving the pose features right now, but it should be simple to have a blank personality feature, right?

**Comment by ghost** [comment]
Here's a build hot off the press that has that implemented. Please test and see if it works for you.

https://mega.nz/#!50lg1BJB!XCjx7s7UVwqMJv1MnVKrVx77GBOZy5keJFwgWDnSIJs

**Comment by chlorine03** [comment]
I'm sorry to bother you, but I don't think it works. Just to make sure, but by blank personality/name, I mean the english personalities (Manly, Playful, etc.) and the character names.

**Comment by ghost** [comment]
I've added a section under the Poses tab that allows you to blank the english personalities in the top left of the card.

If you want to blank character names, you'll have to set them blank by using the Info window that pops up after you load the card in the Card Replacer tab, and then saving it somewhere else. Making this process automatic requires patching of the maker .exe which is outside my level of expertise with this kind of stuff, sorry.

**Comment by chlorine03** [comment]
Ah, sorry, I did not see that. Thank you for the response! Much appreciated.

**Comment by ghost** [comment]
Closed since solved.
