### ISSUE TITLE
Not sure if this is a bug, or I'm doing it wrong, but...

### ISSUE THREAD

**Issue by chlorine03** [aa2g/AA2Snowflake#8]
For some reasons, after I click "Move" on the "Poses" tab, the personality will be set back to "Sweet" no matter which one I had in the "Clothes" tab. It doesn't happen when I don't mess with the poses. So I end up having to use the sweet personality for poses. Now the problem is: the class roster will say "Sweet" no matter what I do, because changing the personality in ReiEdit doesn't actually change the roster image.

Another problem is that after restoring the .pp files, the default characters will always start with the "T" pose.

I'm using your build which has the option to set personality text to blank.

Edit: Looks like updating to the newest version fixed the personality issue. The T pose thing still persists however.

**Comment by ghost** [comment]
The "T" pose issue should be fixed after you restore the pose for any default personality in section 3.2. The reason for why it happens in the first place is something I'm looking into.

**Comment by chlorine03** [comment]
Thanks, that fixed it.
