### ISSUE TITLE
Issues with changing male/male personality poses.

### ISSUE THREAD

**Issue by chlorine03** [aa2g/AA2Snowflake#9]
Do they have different pose numbers compared to the females? So far I've only been getting T-poses on the card when I try to change a male pose. Doesn't happen with females.

**Comment by ghost** [comment]
Yes, they have different pose numbers.

http://imgur.com/DRnldtJ,8GmtcC4,bXDG1Tk,LDkVmgC,chlbl7J,ZIpAux7,F5bEJci,BKtOwf4,IeiUgEF,pY81ySZ,KuWJCW5#0

**Comment by chlorine03** [comment]
Thank you very much.
